In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#Importing the dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/kag_risk_factors_cervical_cancer.csv")
#prints first 10 file in csv
df.head(40)

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,?,?,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,?,?,0,0,0,0,0,0,0,0
2,34,1.0,?,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,?,?,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,0.0,...,?,?,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,...,?,?,0,0,0,0,0,0,0,0
5,42,3.0,23.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,?,?,0,0,0,0,0,0,0,0
6,51,3.0,17.0,6.0,1.0,34.0,3.4,0.0,0.0,1.0,...,?,?,0,0,0,0,1,1,0,1
7,26,1.0,26.0,3.0,0.0,0.0,0.0,1.0,2.0,1.0,...,?,?,0,0,0,0,0,0,0,0
8,45,1.0,20.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,...,?,?,1,0,1,1,0,0,0,0
9,44,3.0,15.0,?,1.0,1.266972909,2.8,0.0,0.0,?,...,?,?,0,0,0,0,0,0,0,0
10,44,3.0,26.0,4.0,0.0,0.0,0.0,1.0,2.0,0.0,...,?,?,0,0,0,0,0,0,0,0
11,27,1.0,17.0,3.0,0.0,0.0,0.0,1.0,8.0,0.0,...,?,?,0,0,0,0,0,0,0,0
12,45,4.0,14.0,6.0,0.0,0.0,0.0,1.0,10.0,1.0,...,?,?,0,0,0,0,0,0,0,0
13,44,2.0,25.0,2.0,0.0,0.0,0.0,1.0,5.0,0.0,...,?,?,0,0,0,0,0,0,0,0
14,43,2.0,18.0,5.0,0.0,0.0,0.0,0.0,0.0,1.0,...,?,?,0,0,0,0,0,0,0,0
15,40,3.0,18.0,2.0,0.0,0.0,0.0,1.0,15.0,0.0,...,?,?,0,0,0,0,0,0,0,0
16,41,4.0,21.0,3.0,0.0,0.0,0.0,1.0,0.25,0.0,...,?,?,0,0,0,0,0,0,0,0
17,43,3.0,15.0,8.0,0.0,0.0,0.0,1.0,3.0,0.0,...,?,?,0,0,0,0,0,0,0,0
18,42,2.0,20.0,?,0.0,0.0,0.0,1.0,7.0,1.0,...,?,?,0,0,0,0,0,0,0,0
19,40,2.0,27.0,?,0.0,0.0,0.0,0.0,0.0,1.0,...,?,?,0,0,0,0,0,0,0,0
20,43,2.0,18.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,...,?,?,0,0,0,0,0,0,0,0
21,41,3.0,17.0,4.0,0.0,0.0,0.0,1.0,10.0,0.0,...,21.0,21.0,0,0,0,0,0,0,0,0
22,40,1.0,18.0,1.0,0.0,0.0,0.0,1.0,0.25,0.0,...,2.0,2.0,0,0,0,0,0,1,1,1
23,40,1.0,20.0,2.0,0.0,0.0,0.0,1.0,15.0,0.0,...,?,?,1,0,1,0,1,1,0,1
24,40,3.0,15.0,3.0,0.0,0.0,0.0,1.0,3.0,0.0,...,?,?,0,0,0,0,0,0,0,0
25,44,3.0,19.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,?,?,0,0,0,0,0,0,0,0
26,39,5.0,23.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,...,?,?,0,0,0,0,0,0,0,0
27,39,2.0,17.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,?,?,0,0,0,0,0,0,0,0
28,37,3.0,24.0,1.0,1.0,3.0,0.04,0.0,0.0,0.0,...,?,?,0,0,0,0,0,0,0,0
29,37,6.0,26.0,1.0,0.0,0.0,0.0,1.0,0.25,0.0,...,?,?,0,0,0,0,0,0,0,0
30,41,3.0,17.0,3.0,0.0,0.0,0.0,1.0,22.0,1.0,...,?,?,0,0,0,0,0,0,0,0
31,40,2.0,21.0,2.0,0.0,0.0,0.0,1.0,19.0,1.0,...,?,?,0,0,0,0,0,0,0,0
32,37,3.0,17.0,5.0,1.0,1.266972909,0.5132021277,1.0,10.0,0.0,...,?,?,0,0,0,0,0,0,0,0
33,37,3.0,15.0,3.0,0.0,0.0,0.0,1.0,0.5,1.0,...,?,?,0,0,0,0,0,0,0,0
34,38,2.0,15.0,2.0,0.0,0.0,0.0,1.0,0.5,1.0,...,?,?,0,0,0,0,0,1,0,0
35,37,3.0,17.0,5.0,0.0,0.0,0.0,1.0,1.0,1.0,...,?,?,0,0,0,0,0,0,0,0
36,39,2.0,17.0,4.0,0.0,0.0,0.0,1.0,1.0,0.0,...,?,?,0,0,0,0,0,0,0,0
37,37,?,18.0,1.0,0.0,0.0,0.0,1.0,0.58,0.0,...,?,?,0,0,0,0,0,0,0,0
38,39,1.0,24.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,...,?,?,0,0,0,0,0,0,0,0
39,36,2.0,20.0,3.0,0.0,0.0,0.0,1.0,2.0,0.0,...,?,?,0,0,0,0,0,0,0,0

In [ ]:
for feature in df.columns:
    df[feature].replace('?',np.nan,inplace=True )
    df[feature].fillna(value=0,inplace=True)
for feature in df.columns:
    df[feature].replace(0,df[feature].median(),inplace=True)
df.head()

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
2,34,1.0,17.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,0.0,...,0.0,0.0,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0

In [ ]:
df.replace(to_replace=np.nan,value=0000)

,Age,Number of sexual partners,First sexual intercourse,Num of pregnancies,Smokes,Smokes (years),Smokes (packs/year),Hormonal Contraceptives,Hormonal Contraceptives (years),IUD,...,STDs: Time since first diagnosis,STDs: Time since last diagnosis,Dx:Cancer,Dx:CIN,Dx:HPV,Dx,Hinselmann,Schiller,Citology,Biopsy
0,18,4.0,15.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
1,15,1.0,14.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
2,34,1.0,17.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
3,52,5.0,16.0,4.0,1.0,37.0,37.0,1.0,3.0,0.0,...,0.0,0.0,1,0,1,0,0,0,0,0
4,46,3.0,21.0,4.0,0.0,0.0,0.0,1.0,15.0,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,34,3.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
854,32,2.0,19.0,1.0,0.0,0.0,0.0,1.0,8.0,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
855,25,2.0,17.0,0.0,0.0,0.0,0.0,1.0,0.08,0.0,...,0.0,0.0,0,0,0,0,0,0,1,0
856,33,2.0,24.0,2.0,0.0,0.0,0.0,1.0,0.08,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0
857,29,2.0,20.0,1.0,0.0,0.0,0.0,1.0,0.5,0.0,...,0.0,0.0,0,0,0,0,0,0,0,0

In [ ]:
from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder
Le = LabelEncoder()

In [ ]:
features = ['Age', 'Dx:CIN', 'Dx:HPV','Dx:Cancer']
xx=features
X = df[features]
y = df['Biopsy']
print(X)
print(y)

     Age  Dx:CIN  Dx:HPV  Dx:Cancer
0     18       0       0          0
1     15       0       0          0
2     34       0       0          0
3     52       0       1          1
4     46       0       0          0
..   ...     ...     ...        ...
853   34       0       0          0
854   32       0       0          0
855   25       0       0          0
856   33       0       0          0
857   29       0       0          0

[858 rows x 4 columns]
0      0
1      0
2      0
3      0
4      0
      ..
853    0
854    0
855    0
856    0
857    0
Name: Biopsy, Length: 858, dtype: int64

In [ ]:
#spliting data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=0)

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.metrics import accuracy_score

In [ ]:
# SVC with linear kernel
C = 1.0 # SVM regularization parameter
# LinearSVC (linear kernel)
svc =SVC(kernel='linear', C=C)
svc.fit(X_train, y_train)
y_pred1 = svc.predict(X_test)
print ('Accuracy-svm', accuracy_score(y_test, y_pred1))

Accuracy-svm 0.9534883720930233

In [ ]:
# SVC with RBF kernel
rbf_svc =SVC(kernel='rbf', gamma=0.8, C=C)
rbf_svc.fit(X_train, y_train)
y_pred2 = rbf_svc.predict(X_test)
print ('Accuracy-svm', accuracy_score(y_test, y_pred2))

Accuracy-svm 0.9476744186046512

In [ ]:
# SVC with polynomial (degree 3) kernel
poly_svc =SVC(kernel='poly', degree=3, C=C)
poly_svc.fit(X, y)
y_pred3 = poly_svc.predict(X_test)
print ('Accuracy-svm:', accuracy_score(y_test, y_pred3))

Accuracy-svm: 0.9534883720930233